db.url=jdbc:mysql://localhost:3306/auction_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
db.username=root
db.password=admin07

# HikariCP pool
db.poolSize=10

# 30 giây ch? l?y connection
db.connectionTimeout=30000

# 10 phút connection idle thì tr? v? pool
db.idleTimeout=600000

# 30 phút t?i ?a 1 connection t?n t?i
db.maxLifetime=1800000